branches:
  only:
    - master
    - feature/ci
    - /^.*travis.*$/

sudo: required

language: node_js

node_js:
  - "stable"

notifications:
  email: false

services:
  - docker

install:
  - cd ./app
  - npm install mkdirp@latest
  - npm install --only=dev
  - npm run build
  - cd ..

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps

script:
  - ./test_curl.sh

after_succes:
  - docker image build -t "${REGISTRY_USER}/spotifinest" ./app
  - docker image build -t "${REGISTRY_USER}/spotifinest-api" ./api

deploy:
  provider: script
  script: docker image push "${REGISTRY_USER}/spotifinest" && docker image push "${REGISTRY_USER}/spotifinest-api"
  on:
    branch: master
