branches:
  only:
    - master
    - feature/ci
    - /^.*travis.*$/

sudo: required

language: node_js

node_js:
  - "stable"

notifications:
  email: false

services:
  - docker

install:
  - cd ./app
  - npm install =only-dev
  - cd ..

before_script:
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker-compose ps

script:
  - ./test_curl.sh

after_succes:
  - docker image build -t "${REGISTRY_USER}/spotifinest" ./app
  - docker image build -t "${REGISTRY_USER}/spotifinest-api" ./api

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker image push "${REGISTRY_USER}/spotifinest" && docker image push "${REGISTRY_USER}/spotifinest-api"
  on:
    branch: master
