version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  spotifinest:
    build: ./app
    environment:
      - VIRTUAL_HOST=spotifinest.svenwesterlaken.nl

  spotifinest-api:
    build: ./api
    environment:
      - FRONTEND_CB_URI=http://spotifinest.svenwesterlaken.nl/callback
      - REDIRECT_URI=http://spotifinest-api.svenwesterlaken.nl/callback
      - VIRTUAL_HOST=spotifinest-api.svenwesterlaken.nl
      - VIRTUAL_PORT=8000
